### ISSUE TITLE
Certificate for www.auroraoss.com invalid

### ISSUE THREAD

**Issue by JohnVeness** [aurora-website/website_v1#4]
Hi. I realise that https://auroraoss.com/ is your canonical domain. Nonetheless I accidentally typed to visit https://www.auroraoss.com/ and got a browser warning that the certificate is invalid. Hopefully this is an easy fix! Thanks for reading.

**Comment by marchingon12** [comment]
I didn't quite get this. Are you saying we should redirect www.auroraoss.com to auroraoss.com or something similar?

**Comment by marchingon12** [comment]
I'll have a chat with our server boi, thnx for the heads up!

**Comment by marchingon12** [comment]
Should be fixed now. If it isn't working just yet, wait for a few hours maybe or clear your cache (or if you added exception for www., remove it).

**Comment by JohnVeness** [comment]
Looks good to me. Thanks!
